name: Gerar cobrinha dos commits

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-24.04

    steps:
      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: ronycorrea
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publicar na branch output
        run: |
          cd dist

          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout -b output
          git add .
          git commit -m "Atualizar cobrinha"

          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

          git push -f origin output
